### ISSUE TITLE
The problem with the slash at the end of the URL

### ISSUE THREAD

**Issue by PhantomArt** [pinepain/php-simple-router#3]
I want to handle addresses with a slash at the end. Example:
`/some-url/posts/{id}/`
But the library finds a match with the URL:
`/some-url/posts/123`
But not:
`/some-url/posts/123/`

**Comment by pinepain** [comment]
Hi Andrey! Thanks for pointing this out.

Obviously, the library itself should make no conclusion which convention end-user follows (slashes or no-slashes, slashes for "directories" only and so on).

At this time, internally, trailing slashes were ignored, which is wrong and will be fixed in a next patch release.
